### PR TITLE
Add 0.18.1 release notes

### PR DESCRIPTION
**Pull request by slotThe**
Nothing too surprising (I hope :)) as it's a relatively small release

### CODE REVIEW

**Comment by TheMC47** [comment]
Shoulf we do something about https://github.com/xmonad/xmonad-contrib/issues/880? I could take a look at it tomorrow

**Comment by slotThe** [comment]
Oh, this must've slipped my mind because it was tagged `0.19.0`, sorry! The easiest cases where people just have a `ScreenId -> StatusBarConfig` don't need to change, so it's probably not all that bad. Still, if you want to take a look at possibly more involved ones that would be great!

**Comment by TheMC47** [comment]
Sure thing, I'll take a look tomorrow. And my bad, I tagged the wrong milestone.

**Comment by slotThe** [comment]
I… don't think there was a 0.18.1 milestone, so no worries!

**Pull request merged**
