### PR TITLE
Update the website to Jekyll

### PR DESCRIPTION
**Pull request by TheMC47**
See #19

### CODE REVIEW

**Comment by eyenx** [comment]
Hmm not sure, but should it be merged into master instead of gh-pages? gh-pages should just hold the resulting html build, right?

**Comment by TheMC47** [comment]
I thought so, but no. GitHub automatically generates the website and serves it if it's a jekyll app

**Comment by TheMC47** [comment]
I messed up somewhere during the rebase...

**Comment by TheMC47** [comment]
I think I fixed all the problems

**Review by eyenx — APPROVED** [review]

**Pull request merged**
