### PR TITLE
Add some keybinds and tidy up

### LINKED ISSUE #287: Update the xmonad cheatsheet
The [current cheatsheet](https://wiki.haskell.org/wikiupload/b/b8/Xmbindings.png) is really nice and still quite up-to-date; with the exception of `M-S-/` missing to bring up and `xmessage` window with the default keybindings.  It would be great to redo it for the next release! 

Indeed, even the [help function](https://github.com/xmonad/xmonad/blob/master/src/XMonad/Config.hs#L289) doesn't mention its own keybinding!  This could be fixed in tandem with the new picture. 

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  ~~- [ ] I tested my configuration with [xmonad-testing](https://github.com/xmonad/xmonad-testing)~~

### PR DESCRIPTION
**Pull request by mzrinsky**
Add keybind for showing default keybinds.
Do some minor cleanup of lines and things,
as long as I was in there already.
Add missing Xinerama keybinds for moving windows.
Add XMonad logo, as it was in the original png,
as it appeared on the haskell wiki.

Fixes: xmonad/xmonad#287

These are the image changes to go along with the documentation change.

Let me know if there needs to be any other changes, or if I should update the version to 0.17 (or 0.16?) was not totally sure, but since I think the current release is 0.15 I went with that.

xmbindings

### CODE REVIEW

**Review by slotThe — APPROVED** [review]
This is really great!  

The only minor nit I noticed is that it says `http://xmonad.org` instead of `https://xmonad.org`. 

> Let me know if there needs to be any other changes, or if I should update the version to 0.17 (or 0.16?) was not totally sure, but since I think the current release is 0.15 I went with that.

I think that that's totally fine.  Updating this to say `0.17` can be done alongside the release and shouldn't cause much trouble

**Review by TheMC47 — APPROVED** [review]
Thanks a lot!

**Comment by mzrinsky** [comment]
I actually added a commit, and squashed, and pushed my branch again, but I think I confused GitHub in the process, as it did not seem to pick up the changes in the current PR?
I did in-fact change the http to https though as you suggested.
Re-viewing the png in this PR does show the changes though, so I think everything is alright?

Attached a copy for easier reference, but looking at the changed file shows the same thing.

xmbindings

Just figured it was such a quick change, I might as well do it.

**Comment by slotThe** [comment]
> I actually added a commit, and squashed, and pushed my branch again, but I think I confused GitHub in the process, as it did not seem to pick up the changes in the current PR?
> I did in-fact change the http to https though as you suggested.
> Re-viewing the png in this PR does show the changes though, so I think everything is alright?

GitHub shows me the force push and the change also seems to be included, so everything is indeed fine.  Thanks!

**Pull request merged**
