### PR TITLE
Update cheatsheet for new version + logo

### PR DESCRIPTION
**Pull request by slotThe**
I'd really like someone else to open the new SVG in inkscape and tell me I didn't break anything; I was quite surprised that things were misaligned the first time around.

##### images: Regenerate cheatsheet with Inkscape 1.1.1

When opening this with Inkscape 1.1.1, text boxes were a tiny bit too
small, misaligning lots of things—fix that.

##### images: Incorporate new logo into cheatsheet

Also update its version.

Related: https://github.com/xmonad/xmonad-web/pull/54

### CODE REVIEW

**Comment by liskin** [comment]
Looking at PNG diffs using github's interface suggests that you kind of did break stuff. I tried to redo what you did on my computer and I haven't encountered any alignment issues, so I ended up with less disruptive changes here: https://github.com/xmonad/xmonad-web/compare/gh-pages...liskin:cheatsheet

It's quite possible, however, that the SVGs I ended up with will misalign on your computer. Still, my commits avoid unrelated changes to the generated PNGs, so I'd go with these :-)

**Comment by slotThe** [comment]
Well all the fonts are installed so... no idea what could be wrong :/

> Still, my commits avoid unrelated changes to the generated PNGs, so I'd go with these :-)

Yeah definitely, let's go with the less-disruptive changes

**Comment by liskin** [comment]
Shall I force push my version into your branch then?

**Comment by slotThe** [comment]
On Fri, Jan 21 2022 12:39, Tomáš Janoušek wrote:
> Shall I force push my version into your branch then?

Sounds good to me!

**Pull request merged**
